export enum Screens {
    LOGIN = 'LOGIN',
    MAIN_TABS = 'MAIN_TABS',
    HOME = 'HOME',
    DOCTORS = 'DOCTORS',
    SHOP = 'SHOP',
    RECORDS = 'RECORDS',
    PROFILE = 'PROFILE',
    WISHLIST = 'WISHLIST',
    DOCTOR_DETAILS = 'DOCTOR_DETAILS',
    BOOKINGS = 'BOOKINGS',
    CART = 'CART',
    PRODUCT_DETAIL = 'PRODUCT_DETAIL'
}

export enum TABS {
    HOME_TAB = 'HOME_TAB',
    DOCTORS_TAB = 'DOCTORS_TAB',
    SHOP_TAB = 'SHOP_TAB',
    RECORDS_TAB = 'RECORDS_TAB',
    WISHLIST_TAB = 'WISHLIST_TAB',
}