export { default as home } from './images/Home.svg'
export { default as doctors } from './images/Doctor.svg'
export { default as doctor } from './images/Doctor.svg'
export { default as shop } from './images/Shop.svg'
export { default as records } from './images/Records.svg'
export { default as profile } from './images/Profile.svg'
export { default as logo } from './images/logo.png'
export { default as search } from './images/SearchIcon.svg'
export { default as filter } from './images/Filter.svg'
export { default as star } from './images/Star.svg'
export { default as briefcase } from './images/Briefcase.svg'
export { default as globe } from './images/Globe.svg'
export { default as verified } from './images/VerifiedIcon.svg'
export { default as cross } from './images/Cross.svg'
export { default as filterClearIcon } from './images/FilterClearIcon.svg'
export { default as noDoctor } from './images/NoDoctor.svg'
export { default as backArrow } from './images/BackArrow.svg'
export { default as heartIcon } from './images/HeartIcon.svg'
export { default as clockIcon } from './images/ClockIcon.svg'
export { default as chevronDown } from './images/ChevronDown.svg'
export { default as sunIcon } from './images/SunIcon.svg'
export { default as arrowRight } from './images/ArrowRight.svg'
export { default as calender } from './images/Calender.svg'
export { default as meet } from './images/Meet.svg'


