export enum QUERY_KEYS {
    DOCTORS = 'DOCTORS',
    DOCTORS_SLOTS = 'DOCTORS_SLOTS',
    BOOK_SLOTS = 'BOOK_SLOTS',
    BOOKINGS = 'BOOKINGS',
    PRODUCTS = 'PRODUCTS',
    CART = 'CART',
    WISHLIST = 'WISHLIST',
    USER = 'USER'
}

